validate key format

diff --git a/deployment/maven-deployment/action.yml b/deployment/maven-deployment/action.yml
--- a/deployment/maven-deployment/action.yml
+++ b/deployment/maven-deployment/action.yml
@@ -47,6 +47,16 @@ inputs:
 runs:
   using: composite
   steps:
+    # for easier debugging / configuration
+    - name: Validate private key format
+      shell: bash
+      run: |
+        output=$(gpg --batch --import --dry-run <(echo "${{ inputs.gpg-private-key }}") 2>&1)
+        if [ $? -ne 0 ]; then
+          echo "Error importing GPG key: $output"
+          exit 1
+        fi
+
     - name: Set up Java and Credentials
       uses: actions/setup-java@v4
       with:
