check if gpg key is publicly known before signing artifact

diff --git a/deployment/maven-deployment/action.yml b/deployment/maven-deployment/action.yml
--- a/deployment/maven-deployment/action.yml
+++ b/deployment/maven-deployment/action.yml
@@ -47,7 +47,7 @@ runs:
         server-id: ${{ inputs.server-id }}
         server-username: MAVEN_USERNAME                 # Env var that holds the central publisher user name
         server-password: MAVEN_CENTRAL_TOKEN            # Env var that holds the central publisher user token
-        gpg-private-key: ${{ inputs.gpg-private-key }} # Substituted with the value stored in the referenced secret
+        gpg-private-key: ${{ inputs.gpg-private-key }}  # Substituted with the value stored in the referenced secret
         gpg-passphrase: MAVEN_GPG_PASSPHRASE            # Env var that holds the key's passphrase
 
     # If we want to deploy a snapshot version, we have to make sure that the version ends with SNAPSHOT
@@ -91,6 +91,23 @@ runs:
         if [ "$(printf "%s\n%s" "$PROPOSED_NEW_VERSION" "$LATEST_VERSION" | sort -V | head -n1)" = "$PROPOSED_NEW_VERSION" ]; then
           echo "Proposed new version is lower than the latest version!"
           echo "$PROPOSED_NEW_VERSION <= $LATEST_VERSION"
+          exit 1
+        fi
+
+    - name: Check if gpg key is shared publicly
+      shell: bash
+      run: |
+        MAIL=gpg --with-colons --list-secret-keys | awk -F: '$1=="uid"{match($10, /<([^>]+)>/, m); if (m[1]) print m[1]}'
+        echo "pulisher adddress: $MAIL"
+        if [[ -z "$MAIL" ]]; then
+          echo "Error: Could not retrieve publisher email address from key." >&2
+          exit 2
+        fi
+
+        # Searching for publicly shared PGP key 
+        if ! gpg --batch --keyserver keys.openpgp.org --search-keys "$MAIL" >/dev/null 2>&1 ; then
+          echo "Error: No PGP key found for $MAIL" >&2
+          echo "Make sure the public key is published and email-verified on keys.openpgp.org" >&2
           exit 1
         fi
 
